AWSTemplateFormatVersion: '2010-09-09'
Description: Security Groups for funds-btg (ALB and ECS)

Resources:
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP from API Gateway VPC Link
      VpcId: !ImportValue funds-btg-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: funds-btg-alb-sg

  EcsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from ALB to ECS on 8080
      VpcId: !ImportValue funds-btg-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref AlbSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: funds-btg-ecs-sg

Outputs:
  AlbSecurityGroupId:
    Value: !Ref AlbSecurityGroup
    Export:
      Name: funds-btg-alb-sg-id
  EcsSecurityGroupId:
    Value: !Ref EcsSecurityGroup
    Export:
      Name: funds-btg-ecs-sg-id